### ISSUE TITLE
Fix body text

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#32]
**Description**
Readability of body text on ckan.org is poor - density of text is unbalanced and text is hard to read.

**Expected behaviour**
When visiting the website, I expect to be able to read the content in an easy manner. I also expect the copy to have sufficient space between individual lines of text so that it's more scannable and readble. 

## Acceptance
- [ ] line height is increased and text is justified

## Tasks
- [ ] increase line height/line spacing - increase to 1.5 or if now 21px, increase to 23-25px
- [ ] text alignment - justified

**Comment by Alex-Pavlyuk** [comment]
@popovayoana deployed, pls check

**Comment by popovayoana** [comment]
@Alex-Pavlyuk looks great, closing as FIXED.
