### ISSUE TITLE
Change hyperlink design

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#33]
**Description**
Although users feel a deep-rooted connection between the blue underline and clickability, the blue underlined hyperlink is a relic from simpler days and looks outdated. The interruptive nature of the blue underline has been shown to impede readability. Not only does the underline disrupt the natural flow of the gaze over text ([according to a Hamburg study](https://vsis-www.informatik.uni-hamburg.de/getDoc.php/publications/119/www2003.pdf)), but it also cuts up the low-hanging letters and makes them harder to decipher. This negative impact on readability led Google [to ditch the underlined link in 2014](https://www.theverge.com/2014/3/13/5503894/google-removes-underlined-links-site-redesign), citing a desire to "improve readability and create an overall cleaner look." Google’s decision certainly fits into the wider trend for interface minimalism and flat design, which sit uneasily with the blue underlined hyperlink.

According to web accessibility guidelines ([WCAG 2.0](https://webaim.org/standards/wcag/)), if links are not underlined, it is required that link text must be discernable from body text by at least a 3:1 contrast ratio.

## Acceptance
- [ ] hyperlink text is red and with no underline
- [ ] all visited hyperlinks change their colour (as google search does - in their case from bright blue to purple-ish colour)
- [ ] all hyperlinks change their style on mouse-over, emphasizing that they are clickable

## Tasks
- [ ] remove the underline from all hyperlinks
- [ ] change colour of all hyperlinks from blue to red #ED5248 (as the red in the logo)
- [ ] make all visited hyperlinks change colour to light red #EF6D6A
- [ ] make all hyperlinks change style on mouse-over:
  - [ ] 1st option: colour changes to dark red #B73C39
  - [ ] 2nd option: underline appear (like on ckan.org/features - see example below)

example
![image](https://user-images.githubusercontent.com/78435662/141613884-686ffa39-24c6-4067-9c61-7f7551e137b9.png)

**Comment by alexmorev** [comment]
Code is already finished

**Comment by Alex-Pavlyuk** [comment]
@popovayoana pls check

**Comment by popovayoana** [comment]
perfect! closing issue as FIXED!
