### ISSUE TITLE
Remove "Read more" type of links from all text blocks

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#34]
**Description**
On ckan.org link text such as "_Read more_", "_Read >_", "_View profile_", "_Visit site_" is added at the end of the short teasers for blog posts/articles. Using links like "Read More", "Click Here", etc is considered a bad practice in general ([WCAG 2.0 Success Criterion 2.4.4 Link Purpose (In Context) (Level A)](https://www.w3.org/TR/WCAG20/#navigation-mechanisms-refs). And althought on ckan.org the scenario is not always connected with lack of context, these link texts are still unnecessary. It is not visually appealing, it adds clutter and disturbs readability. Not to mention that there's general inconsistency - on some pages we have them in blue, on some pages - in red, with/without ">".

**Examples**

Home page (Read more)
![image](https://user-images.githubusercontent.com/78435662/141613801-af939838-c404-48cc-a8b3-763c23b69853.png)

Features page (Read more >)
![image](https://user-images.githubusercontent.com/78435662/141614101-5c93f06f-f315-4399-974b-d727630384e5.png)

Showcase page (Visit site)
![image](https://user-images.githubusercontent.com/78435662/141643645-c50adecc-b2be-495f-a830-8393eb1af29c.png)

Solutions > CKAN for Government page (View profile) 
![image](https://user-images.githubusercontent.com/78435662/141643705-50af47db-aec6-4334-80b0-d9aa8875af0a.png)

Support > Commercial support (Details >) 
![image](https://user-images.githubusercontent.com/78435662/141644410-231eb580-cb2b-4ad1-b6e3-de42b26eef12.png)

Blog page (Read >)
![image](https://user-images.githubusercontent.com/78435662/141644207-afab3068-e510-41fd-ad5b-c559e172a9c2.png)

Events page (Read >)
![image](https://user-images.githubusercontent.com/78435662/141595025-a4de62d8-c0ff-408a-8a48-612f77f96a24.png)

**This is generally a better approach since the link actually gives context but since we aim at universal style and consistency, it should also be removed**
![image](https://user-images.githubusercontent.com/78435662/141645963-63579df4-5e73-474b-898f-1b6eb4f73c13.png)

**Expected behaviour**
When I see a text block/short teaser for blog post, I want to be able to open it by clicking anywhere on it - e.g. I want to be able to open it if I click on the title/avatar/image/icon) so that I don't need to click on "Read More", "Read >", etc.

## Acceptance
- [ ] all "_Read more_", "_Read >_", "_View profile_", "_Visit site_" links from the website are removed and substituted with ability to open the blog/article by clicking on its title and avatar.
- [ ] clicking on the title or avatar of a text block/short teaser of a blog/article opens the link 

## Tasks
- [ ] Remove all "_Read more_", "_Read >_", "_View profile_", "_Visit site_" links from the website
- [ ] Make sure alternative ways to open the link are enabled e.g. make sure clicking on the title a/o avatar of a text block/short teaser of a blog/article opens it

**Comment by popovayoana** [comment]
FIXED.
