### ISSUE TITLE
Fix image alignment 

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#35]
**Description**
We have only three options to align an image in text: full width, left-aligned, right-aligned:

![image](https://user-images.githubusercontent.com/78435662/141642449-5ade31a5-eec9-450d-9c85-578e4f63e5bd.png)

If _left-aligned_, then no spacing between text and image
![image](https://user-images.githubusercontent.com/78435662/141614163-fa6ebbbb-74ee-47ea-b89d-0c4512afee0e.png)

If _right-aligned_, then no spacing between text and image
![image](https://user-images.githubusercontent.com/78435662/141642706-7403fa5d-a26d-4a38-8310-58385aef3911.png)

If _full width_, image does not go full width (even if the image resolution allows it)
![image](https://user-images.githubusercontent.com/78435662/141642581-b36c9871-23eb-4461-bd83-5323c96eb54d.png)

**Expected behaviour**
When aligning an image, I expect different align formats to work properly so that:
- full width format positions the image in full width
- when left/right-aligned, there's a proper spacing between text and image
I also expect to be able to position the image right in the center. 

## Acceptance
- [ ] "align to center" function is enabled
- [ ] enough spacing between text and image is added
- [ ] full width alignment works properly

## Tasks
- [ ] Add space around aligned images (between text and image)
- [ ] Add "align to center" function for image positioning
- [ ] Fix full width format

**Comment by Alex-Pavlyuk** [comment]
we will fix it soon

**Comment by Alex-Pavlyuk** [comment]
fixed pls check @popovayoana 
ps: there is no sense in adding the “center“ option as Full width those are the same thing which is positioning the image center with full width

**Comment by popovayoana** [comment]
@Alex-Pavlyuk yeah but not all images are created equal if you know what i mean... : ))) i mean, not all images are supposed to be stretched to full screen (see example below.). ideally, we want to be able to **keep the original size of the image and still have it in center position** but as this is a minor issue atm, and we have other more imortant priorities, let's focus on them. consider this FIXED. thanks!

![image](https://user-images.githubusercontent.com/78435662/172003478-ea843cc5-7aac-42bf-ace7-227694a5f15c.png)
